development:
  adapter: postgresql
  database: hiperativo
  host: localhost

test:
  adapter: postgresql
  database: hiperativo
  host: localhost

production:
  adapter: postgresql
  database: hiperativo
  host: localhost